export {CategoryArea} from './Categories';
export {FacilityArea} from './FacilityArea';
export {Newsletter} from './Newsletter';
export {PartnerArea} from './PartnerArea';
export {ProductsArea} from './ProductsArea';
export {ProductsOfferArea} from './ProductsOfferArea';
export {Slider} from './Slider';
export {TestimonialArea} from './testimonialArea';
export {ProductSlider} from './ProductSlider';